
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 1000
unfocused_hollow = true

[cursor.style]
shape = "Block"
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 10

[font.normal]
family = "Iosevka Term"
style = "Semibold"

[font.bold]
family = "Iosevka Term"
style = "Extrabold"

[font.italic]
family = "Iosevka Term"
style = "Semibold Italic"

[font.bold_italic]
family = "Iosevka Term"
style = "Extrabold Italic"

[window]
dynamic_padding = true
opacity = 0.9

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action="CreateNewWindow"}
]

[general]
import = [
	"~/.config/alacritty/gruvbox_dark.toml",
]
